// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PublicTransport.Data;

#nullable disable

namespace PublicTransport.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251006124257_InitialCr")]
    partial class InitialCr
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("PublicTransport.Entities.PublicTransportE", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("HoursSinceLastService")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TransportType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("PublicTransports");
                });

            modelBuilder.Entity("PublicTransport.Entities.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Duration")
                        .HasPrecision(10, 2)
                        .HasColumnType("TEXT");

                    b.Property<int?>("PublicTransportId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PublicTransportId");

                    b.ToTable("ServicePlans");
                });

            modelBuilder.Entity("PublicTransport.Entities.ServicePlan", b =>
                {
                    b.HasOne("PublicTransport.Entities.PublicTransportE", null)
                        .WithMany("ServicePlans")
                        .HasForeignKey("PublicTransportId");
                });

            modelBuilder.Entity("PublicTransport.Entities.PublicTransportE", b =>
                {
                    b.Navigation("ServicePlans");
                });
#pragma warning restore 612, 618
        }
    }
}
